version: '3.8'

services:
  gin-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: unibackapp
    ports:
      - "8080:8080" # Maps container port 8080 to host port 8080
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_PORT=33060
      - DATABASE_USER=root
      - DATABASE_PASSWORD=rootpassword
      - DATABASE_NAME=mydb
    depends_on:
      - mysql
    networks:
      - app-network
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: gin
      MYSQL_PASSWORD: ginpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network: